### ISSUE TITLE
add plot title and description

### ISSUE THREAD

**Issue by bph98** [hrbrmstr/metricsgraphics#25]
It would be helpful if mjs_plot carried a couple additional options from the native MetricsGraphics.js utiility, including title and description.  Thank you for providing this excellent capability.

**Comment by hrbrmstr** [comment]
Thx for the kudos and suggestion. Unfortunately, the `htmlwidgets` folks consider it more of a best practice to have the titles/descriptions outside the actual widgets. But, you can actually wrap the widget output with `tags` from `htmtools`.  Various repos in https://github.com/timelyportfolio have examples of using that.
