### ISSUE TITLE
Error when plotting Histogram

### ISSUE THREAD

**Issue by jeromefro** [hrbrmstr/metricsgraphics#26]
Hello, 
I have been trying to plot a histogram, but every time I do so, I get an error.

The code I use is:

mjs_plot(rnorm(10000)) %>%
  mjs_histogram()

And the error I get it is:

Error in data[, x] : incorrect number of dimensions

**Comment by shrektan** [comment]
Encountered the same problem.
Here's my `seesionInfo`.

```r
R version 3.2.0 (2015-04-16)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.0

```

**Comment by hrbrmstr** [comment]
I could not replicate. That same sequence of commands works fine for me.  Here's my session info (note that "local v 0.8.0" has virtually no differences besides documentation and moving some Depends to Imports, so that's probably not the issue):

    > devtools::session_info()
    Session info ------------------------------------------------------------------------------------------------------
     setting  value                       
     version  R version 3.2.0 (2015-04-16)
     system   x86_64, darwin13.4.0        
     ui       RStudio (0.99.442)          
     language (EN)                        
     collate  en_US.UTF-8                 
     tz       America/New_York            

    Packages ----------------------------------------------------------------------------------------------------------
     package         * version date       source        
     devtools        * 1.7.0   2015-01-17 CRAN (R 3.2.0)
     digest          * 0.6.8   2014-12-31 CRAN (R 3.2.0)
     htmltools       * 0.2.6   2014-09-08 CRAN (R 3.2.0)
     htmlwidgets     * 0.4     2015-05-18 CRAN (R 3.2.0)
     jsonlite        * 0.9.16  2015-04-11 CRAN (R 3.2.0)
     magrittr        * 1.5     2014-11-22 CRAN (R 3.2.0)
     metricsgraphics   0.8.0   2015-06-12 local         
     rstudioapi      * 0.3.1   2015-04-07 CRAN (R 3.2.0)
     yaml            * 2.1.13  2014-06-12 CRAN (R 3.2.0)
