### ISSUE TITLE
combine efforts on metricsgraphics

### ISSUE THREAD

**Issue by timelyportfolio** [hrbrmstr/metricsgraphics#5]
There is another [repo](https://github.com/yutannihilation/metricsgraphics) from @yutannihilation working on `htmlwidgets` version of `metricsgraphics`.  Regarding https://github.com/ramnathv/htmlwidgets/issues/64, I thought we should cross-reference https://github.com/yutannihilation/metricsgraphics/issues/3 the projects and let the two developers decide to collaborate if possible.

**Comment by yutannihilation** [comment]
Thanks @timelyportfolio. I will contribute to this repo if possible :+1:

(Since my package is just for my practice of package development, I don't want to compete. Maybe I will rename my package to resolve this name collision.)

**Comment by hrbrmstr** [comment]
roger that! any contributions are most welcome :-)
